#ifndef ANIMATED_GRAPHICS_CONSTANTS_H
#define ANIMATED_GRAPHICS_CONSTANTS_H

#include "types.h"
#include "macros.h"
#include "gba/memory.h"

enum AnimatedGfxType {
    ANIMATED_GFX_TYPE_NONE,
    ANIMATED_GFX_TYPE_NORMAL,

    ANIMATED_GFX_TYPE_NORMAL_ONCE = 3,
    ANIMATED_GFX_TYPE_ALTERNATE,
    ANIMATED_GFX_TYPE_REVERSE_ONCE,
    ANIMATED_GFX_TYPE_REVERSE
};

enum AnimatedGfxId {
    ANIMATED_GFX_ID_CRYSTAL,
    ANIMATED_GFX_ID_WATER_SURFACE,
    ANIMATED_GFX_ID_WATER_DEPTH_1,
    ANIMATED_GFX_ID_WATER_DEPTH_2,
    ANIMATED_GFX_ID_WATER_DEPTH_3,
    ANIMATED_GFX_ID_LAVA_SURFACE_HAZE,
    ANIMATED_GFX_ID_LAVA_BUBBLES,
    ANIMATED_GFX_ID_HEAT_HAZE,
    ANIMATED_GFX_ID_WATER_LEAK_ON_FLOOR,
    ANIMATED_GFX_ID_WATER_LEAK_POURING,
    ANIMATED_GFX_ID_WATER_LEAK_SPLASHING,
    ANIMATED_GFX_ID_MELTDOWN_FLASHING,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_SLOW_1,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_SLOW_2,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_SLOW_3,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_SLOW_4,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_SLOW_5,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_SLOW_6,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_SLOW_7,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_SLOW_8,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_SLOW_9,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_SLOW_10,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_SLOW_11,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_SLOW_12,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_SLOW_13,
    ANIMATED_GFX_ID_SNOW,
    ANIMATED_GFX_ID_OPERATIONS_DECK_GLOW_SOLID,
    ANIMATED_GFX_ID_OPERATIONS_DECK_GLOW_EDGE,
    ANIMATED_GFX_ID_ELEVATOR,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_FAST_1,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_FAST_2,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_FAST_3,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_FAST_4,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_FAST_5,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_FAST_6,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_FAST_7,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_FAST_8,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_FAST_9,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_FAST_10,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_FAST_11,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_FAST_12,
    ANIMATED_GFX_ID_BOILER_ROOM_GEAR_FAST_13,
    ANIMATED_GFX_ID_LAVA_SURFACE,
    ANIMATED_GFX_ID_BG_BUBBLES_1,
    ANIMATED_GFX_ID_BG_BUBBLES_2,
    ANIMATED_GFX_ID_REACTOR_CORE_1,
    ANIMATED_GFX_ID_REACTOR_CORE_2,
    ANIMATED_GFX_ID_REACTOR_CORE_3,
    ANIMATED_GFX_ID_REACTOR_CORE_4,
    ANIMATED_GFX_ID_REACTOR_CORE_5,
    ANIMATED_GFX_ID_RESTRICTED_LAB_TUBE_1,
    ANIMATED_GFX_ID_RESTRICTED_LAB_TUBE_2,
    ANIMATED_GFX_ID_RESTRICTED_LAB_WINDOW_1,
    ANIMATED_GFX_ID_RESTRICTED_LAB_WINDOW_2,
    ANIMATED_GFX_ID_ACID_SURFACE,
    ANIMATED_GFX_ID_ACID_LAYER_1,
    ANIMATED_GFX_ID_ACID_LAYER_2,
    ANIMATED_GFX_ID_ACID_LAYER_3,
    ANIMATED_GFX_ID_VINE_1,
    ANIMATED_GFX_ID_VINE_2,
    ANIMATED_GFX_ID_VINE_3,
    ANIMATED_GFX_ID_VINE_4,
    ANIMATED_GFX_ID_VINE_5,
    ANIMATED_GFX_ID_VINE_6,
    ANIMATED_GFX_ID_VINE_7,
    ANIMATED_GFX_ID_VINE_8,
    ANIMATED_GFX_ID_VINE_9,
    ANIMATED_GFX_ID_VINE_10,
    ANIMATED_GFX_ID_VINE_11,
    ANIMATED_GFX_ID_VINE_12,
    ANIMATED_GFX_ID_SECURITY_CAMERA,

    ANIMATED_GFX_ID_COUNT
};

#define ANIMATED_GFX_SIZE 0x80
#define ANIMATED_GFX_SIZE_16_BITS (ANIMATED_GFX_SIZE / 2)
#define ANIMATED_GFX_EWRAM_BASE (EWRAM_BASE + 0x1B000)
#define ANIMATED_GFX_VRAM_BASE (VRAM_BASE + 0x4000)
#define ANIMATED_GFX_VRAM_END (VRAM_BASE + 0xFF60)
#define ANIMATED_GFX_EWRAM_POS(position) (ANIMATED_GFX_EWRAM_BASE + ANIMATED_GFX_SIZE * (position))
#define ANIMATED_GFX_VRAM_POS(position) (ANIMATED_GFX_VRAM_BASE + ANIMATED_GFX_SIZE * (position))
#define ANIMATED_GFX_VRAM_END_POS(position) (ANIMATED_GFX_VRAM_END - ANIMATED_GFX_SIZE * (position))

#define ANIMATED_GFX_TANK_NBR 4
#define ANIMATED_GFX_TANK_FRAME_DELAY (CONVERT_SECONDS(1.f / 15))
#define ANIMATED_GFX_TANK_SIZE (ANIMATED_GFX_SIZE * ANIMATED_GFX_TANK_NBR)
#define ANIMATED_GFX_TANK_VRAM_POS(position) (VRAM_BASE + 0x4A00 + ANIMATED_GFX_SIZE * (position))
#define ANIMATED_GFX_TANK_POS(type, frame) (ANIMATED_GFX_SIZE * ANIMATED_GFX_TANK_NBR * (type) + ANIMATED_GFX_SIZE * (frame))

#endif /* ANIMATED_GRAPHICS_CONSTANTS_H */
