#ifndef BLOCK_CONSTANTS_H
#define BLOCK_CONSTANTS_H

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, BlockType) {
    BLOCK_TYPE_SHOT_REFORM,
    BLOCK_TYPE_BOMB_REFORM,
    BLOCK_TYPE_SPEED_BOOST_REFORM,
    BLOCK_TYPE_CRUMBLE,

    BLOCK_TYPE_REFORM_COUNT,

    BLOCK_TYPE_MISSILE_NEVER_REFORM = BLOCK_TYPE_REFORM_COUNT,
    BLOCK_TYPE_MISSILE_NO_REFORM,
    BLOCK_TYPE_POWER_BOMB_NEVER_REFORM,
    BLOCK_TYPE_SCREW_ATTACK_NO_REFORM,
    BLOCK_TYPE_SPEED_BOOST_NO_REFORM,
    BLOCK_TYPE_BROKEN,

    BLOCK_TYPE_COUNT
};

MAKE_ENUM(u8, TankType) {
    TANK_TYPE_NONE,
    TANK_TYPE_MISSILE,
    TANK_TYPE_ENERGY,
    TANK_TYPE_POWER_BOMB,
};

MAKE_ENUM(u8, CaaDamageType) ENUM_FLAG {
    CAA_DAMAGE_TYPE_NONE                 = 0,
    CAA_DAMAGE_TYPE_BEAM                 = 1 << 0,
    CAA_DAMAGE_TYPE_BOMB                 = 1 << 1,
    CAA_DAMAGE_TYPE_MISSILE              = 1 << 2,
    CAA_DAMAGE_TYPE_POWER_BOMB           = 1 << 3,
    CAA_DAMAGE_TYPE_SPEEDBOOST           = 1 << 4,
    CAA_DAMAGE_TYPE_SPEEDBOOST_ON_GROUND = 1 << 5,
    CAA_DAMAGE_TYPE_SCREW_ATTACK         = 1 << 6,
    CAA_DAMAGE_TYPE_BOMB_CHAIN           = 1 << 7,
    
    TANK_WEAKNESS = CAA_DAMAGE_TYPE_BEAM | CAA_DAMAGE_TYPE_BOMB | CAA_DAMAGE_TYPE_MISSILE | CAA_DAMAGE_TYPE_POWER_BOMB
};

MAKE_ENUM(u8, BlockLifeType) {
    BLOCK_LIFE_TYPE_NONE,
    BLOCK_LIFE_TYPE_NO_NEVER_REFORM,
    BLOCK_LIFE_TYPE_REFORM,
    BLOCK_LIFE_TYPE_BOMB_CHAIN,
    BLOCK_LIFE_TYPE_TANK
};

MAKE_ENUM(u8, BlockSubType) {
    BLOCK_SUB_TYPE_REFORM,
    BLOCK_SUB_TYPE_SQUARE_NO_REFORM,
    BLOCK_SUB_TYPE_NO_REFORM,
    BLOCK_SUB_TYPE_SQUARE_NEVER_REFORM,
    BLOCK_SUB_TYPE_BOMB_CHAIN,

    BLOCK_SUB_TYPE_COUNT
};

MAKE_ENUM(u8, BombChainType) {
    BOMB_CHAIN_TYPE_VERTICAL_1,
    BOMB_CHAIN_TYPE_VERTICAL_2,
    BOMB_CHAIN_TYPE_VERTICAL_3,
    BOMB_CHAIN_TYPE_VERTICAL_4,
    BOMB_CHAIN_TYPE_HORIZONTAL_1,
    BOMB_CHAIN_TYPE_HORIZONTAL_2,
    BOMB_CHAIN_TYPE_HORIZONTAL_3,
    BOMB_CHAIN_TYPE_HORIZONTAL_4,

    BOMB_CHAIN_TYPE_COUNT
};

MAKE_ENUM(u8, SubBombChainRequest) {
    SUB_BOMB_CHAIN_REQUEST_HORIZONTAL_GOING_UP,
    SUB_BOMB_CHAIN_REQUEST_HORIZONTAL_GOING_DOWN,
    SUB_BOMB_CHAIN_REQUEST_VERTICAL_GOING_LEFT,
    SUB_BOMB_CHAIN_REQUEST_VERTICAL_GOING_RIGHT,

    SUB_BOMB_CHAIN_REQUEST_COUNT
};

/**
 * @brief Value used for a broken block stage when it is revealed but intact
 * 
 */
#define BROKEN_BLOCK_STAGE_INTACT 0xF

#endif /* BLOCK_CONSTANTS_H */