#ifndef COLOR_FADING_CONSTANTS_H
#define COLOR_FADING_CONSTANTS_H

#include "types.h"
#include "macros.h"

// TODO: Copied from mzm, fix the values here
MAKE_ENUM(u8, ColorFadingEffect) {
   COLOR_FADING_NONE,
   COLOR_FADING_FLASH,
   COLOR_FADING_CANCEL,
   COLOR_FADING_WHITE,
   COLOR_FADING_DOOR_TRANSITION,
   COLOR_FADING_FLASH2,
   COLOR_FADING_NO_TRANSITION,
   COLOR_FADING_FLASH_NO_TRANSITION,
   COLOR_FADING_NO_TRANSITION_HUD_HIDE,
   COLOR_FADING_SLOW_WHITE,
   COLOR_FADING_SLOW_BLACK,
   COLOR_FADING_AFTER_ENTER_MOTHER_SHIP,
   COLOR_FADING_ESCAPE_FAILED,
   COLOR_FADING_DEMO_ENDING_AUTO,
   COLOR_FADING_DEMO_ENDING_WITH_INPUT,
   COLOR_FADING_CHOZODIA_ESCAPE,
   COLOR_FADING_TOURIAN_ESCAPE,
   COLOR_FADING_GETTING_FULLY_POWERED,
   COLOR_FADING_RIDLEY_SPAWN,
   COLOR_FADING_STATUE_CUTSCENE,
   COLOR_FADING_INTRO_TEXT,
   COLOR_FADING_LANDING_SHIP,
   COLOR_FADING_SAMUS_IN_BLUE_SHIP,
   COLOR_FADING_TO_WHITE,
   COLOR_FADING_TO_BLACK,

   COLOR_FADING_COUNT
};

MAKE_ENUM(u8, ColorFadingStatus) ENUM_FLAG {
   COLOR_FADING_STATUS_ON_BG =  1 << 0,
   COLOR_FADING_STATUS_ON_OBJ = 1 << 1
};

#endif /* COLOR_FADING_CONSTANTS_H */
