#ifndef CONNECTION_CONSTANTS_H
#define CONNECTION_CONSTANTS_H

enum Area {
    AREA_MAIN_DECK,
    AREA_SECTOR_1,
    AREA_SECTOR_2,
    AREA_SECTOR_3,
    AREA_SECTOR_4,
    AREA_SECTOR_5,
    AREA_SECTOR_6,

    AREA_NORMAL_LAST = AREA_SECTOR_6,
    AREA_NORMAL_COUNT,

    AREA_TEST_1 = AREA_NORMAL_COUNT,
    AREA_TEST_2,
    AREA_TEST_3,

    AREA_END,
};

enum NavigationRoom {
    NAV_ROOM_NONE,
    NAV_ROOM_MAIN_DECK_ROOM_0 = NAV_ROOM_NONE,
    NAV_ROOM_MAIN_DECK_ROOM_16,
    NAV_ROOM_MAIN_DECK_ROOM_9,
    NAV_ROOM_MAIN_DECK_ROOM_32,
    NAV_ROOM_SECTOR_1_ROOM_2,
    NAV_ROOM_SECTOR_5_ROOM_2,
    NAV_ROOM_SECTOR_2_ROOM_2,
    NAV_ROOM_SECTOR_4_ROOM_2,
    NAV_ROOM_SECTOR_3_ROOM_2,
    NAV_ROOM_SECTOR_6_ROOM_2,
    NAV_ROOM_MAIN_DECK_ROOM_56,
    NAV_ROOM_MAIN_DECK_ROOM_66,

    NAV_ROOM_ANY,

    NAV_ROOM_COUNT
};

enum DoorType {
    DOOR_TYPE_NONE,
    DOOR_TYPE_AREA_CONNECTION,
    DOOR_TYPE_NO_HATCH,
    DOOR_TYPE_OPEN_HATCH,
    DOOR_TYPE_HATCH_CAN_LOCK,

    DOOR_TYPE_END,

    DOOR_TYPE_NO_FLAGS = 0xF,

    DOOR_TYPE_NORMAL = (1 << 4),
    DOOR_TYPE_LOAD_EVENT_BASED_ROOM = (1 << 5),
    DOOR_TYPE_DISPLAY_LOCATION_NAME = (1 << 6),
};

enum Elevator {
    ELEVATOR_MAIN_DECK_TO_OPERATIONS_DECK,
    ELEVATOR_MAIN_DECK_TO_LOBBY,
    ELEVATOR_MAIN_DECK_TO_SECTOR_1,
    ELEVATOR_MAIN_DECK_TO_SECTOR_2,
    ELEVATOR_MAIN_DECK_TO_SECTOR_4,
    ELEVATOR_MAIN_DECK_TO_SECTOR_5,
    ELEVATOR_MAIN_DECK_TO_SECTOR_6,
    ELEVATOR_MAIN_DECK_TO_SECTOR_3,
    ELEVATOR_MAIN_DECK_TO_LOBBY_POWER_OUTAGE,
    ELEVATOR_MAIN_DECK_TO_HABITATIONS_DECK,
    ELEVATOR_RESTRICTED_ZONE_TO_SECTOR_1,

    ELEVATOR_END
};

// TODO: Move?
enum NavigationTargetLocation {
    NAV_TARGET_LOC_NONE,
    NAV_TARGET_LOC_OPERATIONS_DECK,
    NAV_TARGET_LOC_DOCKING_BAYS,
    NAV_TARGET_LOC_HABITATION_DECK,
    NAV_TARGET_LOC_MAIN_DECK,
    NAV_TARGET_LOC_REACTOR_SILO,
    NAV_TARGET_LOC_RESTRICTED_LAB,
    NAV_TARGET_LOC_SECTOR_1,
    NAV_TARGET_LOC_SECTOR_2,
    NAV_TARGET_LOC_SECTOR_3,
    NAV_TARGET_LOC_SECTOR_4,
    NAV_TARGET_LOC_SECTOR_5,
    NAV_TARGET_LOC_SECTOR_6,

    NAV_TARGET_LOC_END
};

enum HatchLockType {
    HATCH_LOCK_GRAY,
    HATCH_LOCK_LEVEL_1,
    HATCH_LOCK_LEVEL_2,
    HATCH_LOCK_LEVEL_3,
    HATCH_LOCK_LEVEL_4,
    HATCH_LOCK_CAN_LOCK,
    HATCH_LOCK_OPEN,

    HATCH_LOCK_COUNT
};

enum HatchState {
    HATCH_STATE_CLOSED,
    HATCH_STATE_OPENING,
    HATCH_STATE_OPENED,
    HATCH_STATE_CLOSING,

    HATCH_STATE_COUNT
};

#define HATCH_VERTICAL_SIZE 4

#endif /* CONNECTION_CONSTANTS_H */
