#ifndef ENDING_CONSTANTS_H
#define ENDING_CONSTANTS_H

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, CreditLineType) {
    CREDIT_LINE_TYPE_BLUE,
    CREDIT_LINE_TYPE_RED,
    CREDIT_LINE_TYPE_WHITE_BIG,
    //CREDIT_LINE_TYPE_WHITE_SMALL, // Exists only in ZM

    CREDIT_LINE_TYPE_BLANK = 5,
    CREDIT_LINE_TYPE_END,

    CREDIT_LINE_TYPE_ALL_RIGHTS = 10,
    CREDIT_LINE_TYPE_THE_COPYRIGHT,
    CREDIT_LINE_TYPE_SCENARIO,
    CREDIT_LINE_TYPE_RESERVED
};

#endif /* ENDING_CONSTANTS_H */
