#ifndef GAME_STATE_CONSTANTS_H
#define GAME_STATE_CONSTANTS_H

#include "types.h"
#include "macros.h"

MAKE_ENUM(s8, Language) {
    LANGUAGE_JAPANESE,
    LANGUAGE_HIRAGANA,
    LANGUAGE_ENGLISH,
    LANGUAGE_GERMAN,
    LANGUAGE_FRENCH,
    LANGUAGE_ITALIAN,
    LANGUAGE_SPANISH,

    LANGUAGE_COUNT
};

#endif /* GAME_STATE_CONSTANTS_H */
