#ifndef HAZE_CONSTANTS_H
#define HAZE_CONSTANTS_H

enum HazeValue {
    HAZE_VALUE_NONE,
    HAZE_VALUE_GRADIENT,
    HAZE_VALUE_BG3,
    HAZE_VALUE_BG3_STRONG_WEAK, 
    HAZE_VALUE_BG0,
    HAZE_VALUE_BG3_NONE_WEAK,
    HAZE_VALUE_BG3_BG2_STRONG_WEAK_MEDIUM,
    HAZE_VALUE_BG3_BG2_BG1,
    HAZE_VALUE_POWER_BOMB_EXPANDING,
    HAZE_VALUE_POWER_BOMB_RETRACTING,
    HAZE_VALUE_AFTER_POWER_BOMB,
    HAZE_VALUE_COLD,

    HAZE_VALUE_12,
    HAZE_VALUE_13,
    HAZE_VALUE_14,
};

#endif /* HAZE_CONSTANTS_H */
