#ifndef MINIMAP_CONSTANTS_H
#define MINIMAP_CONSTANTS_H

enum MinimapTileType {
    MINIMAP_TILE_TYPE_UNEXPLORED, // Gray
    MINIMAP_TILE_TYPE_NORMAL, // Pink
    MINIMAP_TILE_TYPE_HIDDEN, // Green

    MINIMAP_TILE_TYPE_COUNT
};

enum MinimapUpdateFlag {
    MINIMAP_UPDATE_FLAG_NONE,
    MINIMAP_UPDATE_FLAG_UPPER_LINE,
    MINIMAP_UPDATE_FLAG_MIDDLE_LINE,
    MINIMAP_UPDATE_FLAG_LOWER_LINE,

    MINIMAP_UPDATE_FLAG_COUNT
};

#endif /* MINIMAP_CONSTANTS_H */
