#ifndef NEW_FILE_INTRO_CONSTANTS_H
#define NEW_FILE_INTRO_CONSTANTS_H

#include "macros.h"

MAKE_ENUM(u8, IntroInSr388OamType) {
	INTRO_IN_SR388_OAM_TYPE_SAMUS = 1,
	INTRO_IN_SR388_OAM_TYPE_LEFT_RESEARCHER,
	INTRO_IN_SR388_OAM_TYPE_RIGHT_RESEARCHER,
	INTRO_IN_SR388_OAM_TYPE_HORNOAD_UNUSED,
	INTRO_IN_SR388_OAM_TYPE_HORNOAD_UNUSED_2,
	INTRO_IN_SR388_OAM_TYPE_HORIZONTAL_MISSILE,
	INTRO_IN_SR388_OAM_TYPE_FIRST_DIAGONAL_MISSILE,
	INTRO_IN_SR388_OAM_TYPE_MISSILE_TRAIL,
	INTRO_IN_SR388_OAM_TYPE_HORNOAD,
	INTRO_IN_SR388_OAM_TYPE_MISSILE_EXPLOSION_BIG,
	INTRO_IN_SR388_OAM_TYPE_UNK_11,
	INTRO_IN_SR388_OAM_TYPE_CAVE_ENTRANCE_BG,
	INTRO_IN_SR388_OAM_TYPE_BLACK_RECTANGLE,
	INTRO_IN_SR388_OAM_TYPE_SECOND_DIAGONAL_MISSILE,

	INTRO_IN_SR388_OAM_TYPE_NEXT_PAGE_ARROW = 50,

	INTRO_IN_SR388_OAM_TYPE_UNK_255 = UCHAR_MAX
};

#endif /* NEW_FILE_INTRO_CONSTANTS_H */
