#ifndef ROOM_CONSTANTS_H
#define ROOM_CONSTANTS_H

#include "types.h"
#include "macros.h"

enum RoomScrollsFlag {
    ROOM_SCROLLS_FLAG_NO_SCROLLS = 2,
    ROOM_SCROLLS_FLAG_HAS_SCROLLS
};

enum RoomEffect {
    EFFECT_NONE,
    EFFECT_WATER,
    EFFECT_LAVA,
    EFFECT_LAVA_HEAT_HAZE,
    EFFECT_ACID,
    EFFECT_SNOWFLAKES_COLD_KNOCKBACK,
    EFFECT_SNOWFLAKES_COLD,

    EFFECT_HAZARD_COUNT,

    EFFECT_HEAT_BG3_HAZE = EFFECT_HAZARD_COUNT,
    EFFECT_HEAT_BG2_BG3_HAZE,
    EFFECT_BG3_GRADIENT,
    EFFECT_BG2_GRADIENT,
    EFFECT_HAZE_BG1_BG2_BG3,

    EFFECT_HAZE_COUNT
};

enum BgProperty {
    BG_PROP_NONE,

    BG_PROP_RLE_COMPRESSED = 1 << 4,
    BG_PROP_LZ77_COMPRESSED = 1 << 6,

    BG_PROP_DISABLE_TRANSPARENCY = BG_PROP_RLE_COMPRESSED | 2,
    BG_PROP_13 = BG_PROP_RLE_COMPRESSED | 3, // Main elevator room?
    BG_PROP_14 = BG_PROP_RLE_COMPRESSED | 4,

    BG_PROP_NIGHTMARE_ROOM = BG_PROP_LZ77_COMPRESSED | 1,
    BG_PROP_DARK_ROOM = BG_PROP_LZ77_COMPRESSED | 3,
    BG_PROP_SA_X_ROOM = BG_PROP_LZ77_COMPRESSED | 4,
    BG_PROP_DIM_ROOM = BG_PROP_LZ77_COMPRESSED | 5,
    BG_PROP_WATER_DRAIN_ROOM = BG_PROP_LZ77_COMPRESSED | 6,
    BG_PROP_FOG = BG_PROP_LZ77_COMPRESSED | 7,
    BG_PROP_MELTDOWN = BG_PROP_LZ77_COMPRESSED | 8,
    BG_PROP_NIGHTMARE_SHADOW = BG_PROP_LZ77_COMPRESSED | 9,
    BG_PROP_SR388 = BG_PROP_LZ77_COMPRESSED | 10
};

#endif /* ROOM_CONSTANTS_H */
