#ifndef SAMUS_CONSTANTS_H
#define SAMUS_CONSTANTS_H

#include "types.h"
#include "macros.h"

enum SamusPose {
    SPOSE_STANDING,
    SPOSE_TURNING_AROUND,
    SPOSE_SHOOTING,
    SPOSE_RUNNING,
    SPOSE_MID_AIR,
    SPOSE_TURNING_AROUND_MID_AIR,
    SPOSE_LANDING,
    SPOSE_CROUCHING,
    SPOSE_TURNING_AROUND_AND_CROUCHING,
    SPOSE_SHOOTING_AND_CROUCHING,
    SPOSE_STARTING_SPIN_JUMP,
    SPOSE_SPINNING,
    SPOSE_MORPHING,
    SPOSE_MORPH_BALL,
    SPOSE_ROLLING,
    SPOSE_UNMORPHING,
    SPOSE_MORPH_BALL_MID_AIR,
    SPOSE_GETTING_HURT,
    SPOSE_GETTING_HURT_IN_MORPH_BALL,
    SPOSE_GETTING_KNOCKED_BACK,
    SPOSE_GETTING_KNOCKED_BACK_IN_MORPH_BALL,
    SPOSE_STARTING_WALL_JUMP,
    SPOSE_WALL_JUMPING,
    SPOSE_USING_ELEVATOR,
    SPOSE_HANGING_ON_LEDGE,
    SPOSE_PULLING_UP_FROM_HANGING,
    SPOSE_PULLING_FORWARD_FROM_HANGING,
    SPOSE_PULLING_INTO_MORPH_FROM_HANGING,
    SPOSE_LOWERING_DOWN_TO_START_HANGING,
    SPOSE_SPACE_JUMPING,
    SPOSE_SCREW_ATTACKING,
    SPOSE_SKIDDING,
    SPOSE_ON_SAVE_PAD,
    SPOSE_ON_RECHARGE_OR_SECURITY_PAD,
    SPOSE_TURNING_AROUND_TO_RECHARGE_OR_UNLOCK_DOORS,
    SPOSE_DELAY_BEFORE_SHINESPARKING,
    SPOSE_SHINESPARKING,
    SPOSE_DELAY_AFTER_SHINESPARKING,
    SPOSE_HANGING_FROM_VERTICAL_LADDER,
    SPOSE_STARTING_TO_HOLD_ARM_OUT_ON_VERTICAL_LADDER,
    SPOSE_HOLDING_ARM_OUT_ON_VERTICAL_LADDER,
    SPOSE_SHOOTING_ON_VERTICAL_LADDER,
    SPOSE_STARTING_TO_PUT_ARM_AWAY_ON_VERTICAL_LADDER,
    SPOSE_HANGING_ON_HORIZONTAL_LADDER,
    SPOSE_MOVING_ON_HORIZONTAL_LADDER,
    SPOSE_TURNING_AROUND_ON_HORIZONTAL_LADDER,
    SPOSE_DELAY_AFTER_SHOOTING_ON_HORIZONTAL_LADDER,
    SPOSE_SHOOTING_ON_HORIZONTAL_LADDER,
    SPOSE_FROZEN,
    SPOSE_FROZEN_AND_FALLING,
    SPOSE_FROZEN_IN_MORPH_BALL,
    SPOSE_FROZEN_IN_MORPH_BALL_AND_FALLING,
    SPOSE_UNLOCKING_SECURITY,
    SPOSE_SAVING,
    SPOSE_ON_NAVIGATION_PAD,
    SPOSE_DOWNLOADING_ABILITY,
    SPOSE_BEING_RECHARGED,
    SPOSE_FACING_FOREGROUND,
    SPOSE_FACING_BACKGROUND,
    SPOSE_UNLOCKING_HABITATIONS_DECK,
    SPOSE_GRABBED_BY_ZAZABI,
    SPOSE_LOADING_SAVE,
    SPOSE_DYING,
    SPOSE_HIT_BY_OMEGA_METROID,
    SPOSE_GRABBED_BY_YAKUZA,
    
    SPOSE_END,

    // Sub frame poses
    SPOSE_F7 = 0xF7,
    SPOSE_F8,
    SPOSE_KNOCKBACK_REQUEST,
    SPOSE_HURT_REQUEST,
    SPOSE_FROZEN_REQUEST,
    SPOSE_FC = 0xFC,
    SPOSE_LANDING_REQUEST,
    SPOSE_MID_AIR_REQUEST,
    SPOSE_NONE
};

enum SamusStandingStatus {
    STANDING_GROUND,
    STANDING_ENEMY,
    STANDING_MID_AIR,
    STANDING_NOT_IN_CONTROL,

    STANDING_INVALID = UCHAR_MAX
};

enum SecurityLevel {
    SECURITY_LEVEL_0,
    SECURITY_LEVEL_1,
    SECURITY_LEVEL_2,
    SECURITY_LEVEL_3,
    SECURITY_LEVEL_4,

    SECURITY_LEVEL_END,

    SECURITY_LEVEL_NO_HATCHES = UCHAR_MAX
};

enum ArmCannonDirection {
    ACD_NONE,
    ACD_FORWARD,
    ACD_DIAGONAL_UP,
    ACD_DIAGONAL_DOWN,
    ACD_UP,
    ACD_DOWN,

    ACD_END
};

enum ArmCannonOffsetFields {
    ACO_Y,
    ACO_X,

    ACO_COUNT
};

enum DiagonalAim {
    DIAG_AIM_NONE,
    DIAG_AIM_UP,
    DIAG_AIM_DOWN,

    DIAG_AIM_END
};

enum SlopeType {
    SLOPE_NONE,
    SLOPE_STEEP,
    SLOPE_SLIGHT
};

enum EnvEffect {
    ENV_EFFECT_NONE,
    ENV_EFFECT_WALKING_ON_WET_GROUND,
    ENV_EFFECT_WALKING_ON_BUBBLY_GROUND,
    ENV_EFFECT_WALKING_ON_DUSTY_GROUND,
    ENV_EFFECT_WALKING_ON_VERY_DUSTY_GROUND,
    ENV_EFFECT_JUMPING_IN_OR_OUT_OF_WATER,
    ENV_EFFECT_WALKING_IN_OR_OUT_OF_WATER,
    ENV_EFFECT_TAKING_DAMAGE_IN_LAVA,
    ENV_EFFECT_LANDING_ON_WET_GROUND,
    ENV_EFFECT_LANDING_ON_BUBBLY_GROUND,
    ENV_EFFECT_LANDING_ON_DUSTY_GROUND,
    ENV_EFFECT_LANDING_ON_VERY_DUSTY_GROUND,
    ENV_EFFECT_SKIDDING_ON_WET_GROUND,
    ENV_EFFECT_SKIDDING_ON_DUSTY_GROUND,
    ENV_EFFECT_BREATHING_BUBBLES,

    ENV_EFFECT_END
};

enum EnvEffectRequest {
    ENV_REQUEST_GROUND_EFFECT,
    ENV_REQUEST_SKIDDING_EFFECT,
    ENV_REQUEST_LANDING_EFFECT,
    ENV_REQUEST_JUMPING_IN_OR_OUT_OF_WATER,
    ENV_REQUEST_WALKING_IN_OR_OUT_OF_WATER,
    ENV_REQUEST_BREATHING_BUBBLES
};

#define ARM_CANNON_OAM_ORDER_NONE 0
#define ARM_CANNON_OAM_ORDER_IN_FRONT (1 << 12)
#define ARM_CANNON_OAM_ORDER_BEHIND (1 << 13)

enum SamusNewProjectile {
    NEW_PROJ_NONE,
    NEW_PROJ_BEAM,
    NEW_PROJ_MISSILE,
    NEW_PROJ_3,
    NEW_PROJ_BOMB,
    NEW_PROJ_CHARGED_BEAM,
    NEW_PROJ_POWER_BOMB,

    NEW_PROJ_END
};

enum SamusCollisionType {
    SCT_STANDING,
    SCT_MID_AIR,
    SCT_CROUCHED,
    SCT_3,
    SCT_SPINNING,
    SCT_MORPH_BALL,
    SCT_MORPH_BALL_MID_AIR,

    SCT_END
};

enum SamusHitboxType {
    SAMUS_HITBOX_TYPE_STANDING,
    SAMUS_HITBOX_TYPE_MID_AIR,
    SAMUS_HITBOX_TYPE_CROUCHED,
    SAMUS_HITBOX_TYPE_UNK_3,
    SAMUS_HITBOX_TYPE_MORPHED,
    SAMUS_HITBOX_TYPE_SPINNING,
    SAMUS_HITBOX_TYPE_HANGING,

    SAMUS_HITBOX_TYPE_COUNT
};

enum SamusCollisionDataFields {
    SCDF_HITBOX,
    SCDF_UNK_1,
    SCDF_UNK_2,
    SCDF_UNK_3,
    SCDF_STANDING_STATUS,

    SCDF_COUNT
};

enum SamusHitbox {
    SAMUS_HITBOX_LEFT,
    SAMUS_HITBOX_RIGHT,
    SAMUS_HITBOX_TOP,

    SAMUS_HITBOX_END
};

enum SamusDestructingAction {
    SDA_NONE,
    SDA_SPEED_BOOSTER,
    SDA_SCREW_ATTACK,
    SDA_SCREW_ATTACK_SPEED_BOOSTER,
    SDA_SPEED_BOOSTER_ON_GROUND
};

// --- Flags ---

#define SMF_NONE 0
#define SMF_HIGH_JUMP (1 << 0)
#define SMF_SPEED_BOOSTER (1 << 1)
#define SMF_SPACE_JUMP (1 << 2)
#define SMF_SCREW_ATTACK (1 << 3)
#define SMF_VARIA_SUIT (1 << 4)
#define SMF_GRAVITY_SUIT (1 << 5)
#define SMF_MORPH_BALL (1 << 6)
#define SMF_SA_X_SUIT (1 << 7)

#define BF_NONE 0
#define BF_CHARGE_BEAM (1 << 0)
#define BF_WIDE_BEAM (1 << 1)
#define BF_PLASMA_BEAM (1 << 2)
#define BF_WAVE_BEAM (1 << 3)
#define BF_ICE_BEAM (1 << 4)

#define MBF_NONE 0
#define MBF_MISSILES (1 << 0)
#define MBF_SUPER_MISSILES (1 << 1)
#define MBF_ICE_MISSILES (1 << 2)
#define MBF_DIFFUSION_MISSILES (1 << 3)
#define MBF_BOMBS (1 << 4)
#define MBF_POWER_BOMBS (1 << 5)
#define MBF_ANY_MISSILE (MBF_MISSILES | MBF_SUPER_MISSILES | MBF_ICE_MISSILES | MBF_DIFFUSION_MISSILES)

#define WH_NONE (0 << 0)
#define WH_MISSILES (1 << 0)
#define WH_POWER_BOMB (1 << 4)

#define SCD_NONE (0 << 0)
#define SCD_TOP_LEFT_MOST (1 << 0)
#define SCD_TOP_LEFT_MIDDLE (1 << 1)
#define SCD_TOP_RIGHT_MIDDLE (1 << 2)
#define SCD_TOP_RIGHT_MOST (1 << 3)
#define SCD_SLOPE (1 << 4)

// --- Collision ---

// How far horizontally the range for a ledge grab is
#define SAMUS_LEDGE_GRAB_X_RANGE (HALF_BLOCK_SIZE)

// --- Forced movement ---

#define FORCED_MOVEMENT_UPWARDS_SHINESPARK 0
#define FORCED_MOVEMENT_SIDEWARDS_SHINESPARK 1
#define FORCED_MOVEMENT_DIAGONAL_SHINESPARK 2

#define FORCED_MOVEMENT_MID_AIR_FALL 0
#define FORCED_MOVEMENT_MID_AIR_JUMP 1
#define FORCED_MOVEMENT_MID_AIR_CARRY 2
#define FORCED_MOVEMENT_MID_AIR_DROP 3

#define FORCED_MOVEMENT_BOMB_JUMP 0
#define FORCED_MOVEMENT_BOMB_JUMP_RIGHT 10
#define FORCED_MOVEMENT_BOMB_JUMP_UP 11
#define FORCED_MOVEMENT_BOMB_JUMP_LEFT 12
#define FORCED_MOVEMENT_BOMB_JUMP_ABOVE 0x80

#define FORCED_MOVEMENT_MORPH_BALL_BOUNCE_AFTER_FALL 1
#define FORCED_MOVEMENT_MORPH_BALL_BOUNCE_BEFORE_JUMP ONE_THIRD_SECOND


// --- Velocity ---

#define SAMUS_HIGH_JUMP_VELOCITY (SUB_PIXEL_TO_VELOCITY(QUARTER_BLOCK_SIZE + EIGHTH_BLOCK_SIZE + PIXEL_SIZE - ONE_SUB_PIXEL * .5f))
#define SAMUS_LOW_JUMP_VELOCITY (SUB_PIXEL_TO_VELOCITY(QUARTER_BLOCK_SIZE + PIXEL_SIZE + ONE_SUB_PIXEL + ONE_SUB_PIXEL * .25f))

#define SAMUS_WALL_JUMP_X_VELOCITY (SUB_PIXEL_TO_VELOCITY(EIGHTH_BLOCK_SIZE))

#define SAMUS_Y_ACCELERATION (SUB_PIXEL_TO_VELOCITY(ONE_SUB_PIXEL * .75f))
#define SAMUS_Y_VELOCITY_CAP (SUB_PIXEL_TO_VELOCITY(QUARTER_BLOCK_SIZE))

#define SAMUS_MID_AIR_X_ACCELERATION (SUB_PIXEL_TO_VELOCITY(ONE_SUB_PIXEL))
#define SAMUS_MID_AIR_MORPHED_X_VELOCITY_CAP (SUB_PIXEL_TO_VELOCITY(PIXEL_SIZE + ONE_SUB_PIXEL))
#define SAMUS_X_ACCELERATION (SUB_PIXEL_TO_VELOCITY(ONE_SUB_PIXEL * .75f))
#define SAMUS_MID_AIR_X_VELOCITY_CAP (SUB_PIXEL_TO_VELOCITY(PIXEL_SIZE + PIXEL_SIZE / 2))
#define SAMUS_X_VELOCITY_CAP (SUB_PIXEL_TO_VELOCITY(EIGHTH_BLOCK_SIZE + PIXEL_SIZE))

#define SAMUS_TERMINAL_VELOCITY (SUB_PIXEL_TO_VELOCITY(HALF_BLOCK_SIZE - PIXEL_SIZE - ONE_SUB_PIXEL / 2.f))

#define SKIDDING_VELOCITY_LOSS (SUB_PIXEL_TO_VELOCITY(ONE_SUB_PIXEL + ONE_SUB_PIXEL / 4.f))

#define HORIZONTAL_LADDER_X_VELOCITY (SUB_PIXEL_TO_VELOCITY(PIXEL_SIZE))

#define KNOCKBACK_Y_VELOCITY (SUB_PIXEL_TO_VELOCITY(PIXEL_SIZE * 2))
#define KNOCKBACK_X_VELOCITY (SUB_PIXEL_TO_VELOCITY(PIXEL_SIZE + PIXEL_SIZE / 2))

#define HURT_Y_VELOCITY (SUB_PIXEL_TO_VELOCITY(EIGHTH_BLOCK_SIZE + PIXEL_SIZE))
#define HURT_X_VELOCITY (SUB_PIXEL_TO_VELOCITY(PIXEL_SIZE + PIXEL_SIZE / 2.f))

#define SAMUS_BOMB_BOUNCE_X_VELOCITY (SUB_PIXEL_TO_VELOCITY(PIXEL_SIZE + ONE_SUB_PIXEL))
#define SAMUS_BOMB_BOUNCE_Y_VELOCITY (SUB_PIXEL_TO_VELOCITY(EIGHTH_BLOCK_SIZE))

#define SAMUS_X_SPEEDBOOST_VELOCITY_CAP (SUB_PIXEL_TO_VELOCITY(QUARTER_BLOCK_SIZE + PIXEL_SIZE))

#define SAMUS_DIAGONAL_SHINESPARK_X_VELOCITY (SUB_PIXEL_TO_VELOCITY(QUARTER_BLOCK_SIZE + PIXEL_SIZE))
#define SAMUS_DIAGONAL_SHINESPARK_Y_VELOCITY (SUB_PIXEL_TO_VELOCITY(EIGHTH_BLOCK_SIZE + PIXEL_SIZE))

#define SAMUS_SIDEWARD_SHINESPARK_X_VELOCITY (SUB_PIXEL_TO_VELOCITY(QUARTER_BLOCK_SIZE + EIGHTH_BLOCK_SIZE))

// --- Misc ---

// 1000 frames, 16.6 seconds
#define SAMUS_ITEM_PMT (CONVERT_SECONDS(16.f) + TWO_THIRD_SECOND)
#define SAMUS_FROZEN_DURATION (CONVERT_SECONDS(1.f) + ONE_THIRD_SECOND)

#define CHARGE_BEAM_THRESHOLD CONVERT_SECONDS(1.f + 1.f / 15)
#define CHARGE_BEAM_MAX_THRESHOLD (CHARGE_BEAM_THRESHOLD + CONVERT_SECONDS(.25f))

#endif /* SAMUS_CONSTANTS_H */
