#ifndef STATUS_SCREEN_CONSTANTS_H
#define STATUS_SCREEN_CONSTANTS_H

enum StatusScreenSection {
    BEAM_UPGRADES,
    MISSILE_UPGRADES,
    BOMB_UPGRADES,
    SUIT_UPGRADES,
    MISC_UPGRADES,
    ENERGY_CURRENT,
    ENERGY_MAX,
    MISSILES_CURRENT,
    MISSILES_MAX,
    POWERBOMBS_CURRENT,
    POWERBOMBS_MAX
};

#endif /* STATUS_SCREEN_CONSTANTS_H */